### ISSUE TITLE
大佬可以加一个修改对应字段的数据的方法吗

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [hotWater-me/treeStructureHandle#28]

**Comment by hotWater-me** [comment]
没理解你意思，你可以说下你原本的值和你期望的值。

**Comment by shenhaoguangDayDayUp** [comment]
> 没理解你意思，你可以说下你原本的值和你期望的值。
比如说我想修改 id = 1 的那条数据上的某个字段的值(例如select,我想改成false) 
```
{
 id:1,
 chidren:[],
 select:true,
perentID:'222'
}
```
然后返回一个 修改后的树形结构的数据

**Comment by hotWater-me** [comment]
其实就是递归修改下面的键值，你可以改造下main.js里面的方法，或者麻烦一点 你把数据一维化修改之后 再拼接起来，我最近比较忙 这个需求，可能一到两周我会加上。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月13日(周四) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hotWater-me/treeStructureHandle] 大佬可以加一个修改对应字段的数据吗 (Issue #28)




  
没理解你意思，你可以说下你原本的值和你期望的值。
 比如说我想修改 id = 1 的那条数据上的某个字段的值(例如select,我想改成false)
  {  id:1,  chidren:[],  select:true, perentID:'222' }  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shenhaoguangDayDayUp** [comment]
好的,我试试

**Comment by hotWater-me** [comment]
> 好的,我试试

我添加上这个方法了。
